trigger:
- master

pool:
  name: default
  demands: []

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - checkout: self
      submodules: true
      displayName: 'Checkout'
    - task: CMake@1
      displayName: 'CMake Configure'
      inputs:
        cmakeArgs: '$(Build.SourcesDirectory)'
    - task: CMake@1
      displayName: 'CMake Release'
      inputs:
        cmakeArgs: '--build .'
    - task: CopyFiles@2
      displayName: 'Copy build'
      inputs:
        SourceFolder: 'build/'
        contents: '**'
        targetFolder: '$(Pipeline.Workspace)'

- stage: Test
  dependsOn: Build
  jobs:
  - job: Test
    steps:
    - checkout: none
    - script: |
        ctest -T Test --verbose --output-on-failure
      displayName: 'Run CTest'
      workingDirectory: '$(Pipeline.Workspace)'

- stage: Publish
  dependsOn:
  - Build
  - Test
  condition: 'always()'
  jobs:
  - job: Publish
    steps:
    - task: CopyFiles@2
      displayName: 'Copy test results'
      inputs:
        SourceFolder: '$(Pipeline.Workspace)'
        contents: |
          HelloCMake
          Testing/**
        targetFolder: '$(Build.ArtifactStagingDirectory)'
    - publish: '$(Build.ArtifactStagingDirectory)'
      displayName: 'Publish'
      artifact: drop
