trigger:
- master

pool:
  name: default
  demands: []

stages:
- stage: Build
  jobs:
  - job: Build
    workspace:
      clean: all
    steps:
    - template: templates/print-date.yml
      parameters:
        displayName: 'Build Start time'
    - task: CMake@1
      displayName: 'CMake Configure'
      inputs:
        cmakeArgs: '-S $(Build.SourcesDirectory) -B $(Pipeline.Workspace)/build'
    - task: CMake@1
      displayName: 'CMake Build'
      inputs:
        cmakeArgs: '--build $(Pipeline.Workspace)/build'

- stage: Test
  dependsOn: Build
  jobs:
  - job: Test
    steps:
    - template: templates/print-date.yml
      parameters:
        displayName: 'Test Start time'
    - checkout: none
    - task: CMake@1
      displayName: 'CMake Run Tests'
      inputs:
        cmakeArgs: '--build $(Pipeline.Workspace)/build --target test'
    - task: PublishTestResults@2
      condition: 'succeededOrFailed()'
      inputs:
        testResultsFiles: |
          $(Pipeline.Workspace)/build/test/*.xml
        testRunTitle: 'GoogleTest Results'

- stage: Publish
  dependsOn: Test
  jobs:
  - job: Publish
    steps:
    - template: templates/print-date.yml
      parameters:
        displayName: 'Publish Start time'
    - checkout: none
    - script: |
        tar zcf "$(Build.ArtifactStagingDirectory)/HelloCMake-$(cat version.txt).tar.gz" HelloCMake libSensorData.so
      workingDirectory: '$(Pipeline.Workspace)/build'
      displayName: Compress
    - publish: '$(Build.ArtifactStagingDirectory)'
      displayName: 'Publish'
      artifact: drop
