trigger:
- master

pool:
  name: default
  demands: []

stages:
- stage: Build
  jobs:
  - job: Build
    workspace:
      clean: all
    steps:
    - checkout: self
      submodules: true
      displayName: 'Checkout'
    - task: CMake@1
      displayName: 'CMake Configure'
      inputs:
        cmakeArgs: '$(Build.SourcesDirectory)'
    - task: CMake@1
      displayName: 'CMake Release'
      inputs:
        cmakeArgs: '--build .'
    - task: CopyFiles@2
      displayName: 'Copy build'
      inputs:
        SourceFolder: 'build/'
        contents: '**'
        targetFolder: '$(Pipeline.Workspace)/build'

- stage: Test
  dependsOn: Build
  jobs:
  - job: Test
    steps:
    - checkout: none
    - script: |
        ctest --verbose
      displayName: 'Run CTest'
      workingDirectory: '$(Pipeline.Workspace)/build'
    - task: PublishTestResults@2
      condition: 'succeededOrFailed()'
      inputs:
        testResultsFiles: |
          $(Pipeline.Workspace)/build/test/*.xml
        testRunTitle: 'GoogleTest Results'

- stage: Publish
  dependsOn: Test
  jobs:
  - job: Publish
    steps:
    - checkout: none
    - script: |
        tar zcf "HelloCMake-$(cat version.txt).tar.gz" HelloCMake libSensorData.so
      workingDirectory: '$(Pipeline.Workspace)/build'
      displayName: Compress
    - task: CopyFiles@2
      displayName: 'Copy artifacts'
      inputs:
        SourceFolder: '$(Pipeline.Workspace)/build'
        contents: |
          HelloCMake-*.tar.gz
        targetFolder: '$(Build.ArtifactStagingDirectory)'
    - publish: '$(Build.ArtifactStagingDirectory)'
      displayName: 'Publish'
      artifact: drop
