trigger:
- master

pool:
  name: default
  demands: []

steps:
- checkout: self
  submodules: true
  displayName: 'Checkout'
- task: CMake@1
  displayName: 'CMake Configure'
  inputs:
    cmakeArgs: '..'
- task: CMake@1
  displayName: 'CMake Release'
  inputs:
    cmakeArgs: '--build .'
- script: 'ctest --verbose'
  displayName: 'Run CTest'
  workingDirectory: build
